<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="09285-002L" name="testSmoke" tests="2" failures="2" timestamp="24 Dec 2018 07:16:57 GMT" time="5.975" errors="0">
  <testcase name="ActivaeEbill" time="1.468" classname="crm.telbiz.api.calls.TestApp">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at crm.telbiz.api.calls.TestApp.ActivaeEbill(TestApp.java:186)
	at crm.telbiz.api.calls.Sheduler.main(Sheduler.java:16)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- ActivaeEbill -->
  <testcase name="eEbillRegStatusAPI" time="0.708" classname="crm.telbiz.api.calls.TestApp">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at crm.telbiz.api.calls.TestApp.eEbillRegStatusAPI(TestApp.java:53)
	at crm.telbiz.api.calls.Sheduler.main(Sheduler.java:16)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- eEbillRegStatusAPI -->
</testsuite> <!-- testSmoke -->
