<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke" duration-ms="5975" started-at="2018-12-24T07:16:51Z" finished-at="2018-12-24T07:16:57Z">
    <groups>
    </groups>
    <test name="testSmoke" duration-ms="5975" started-at="2018-12-24T07:16:51Z" finished-at="2018-12-24T07:16:57Z">
      <class name="crm.telbiz.api.calls.TestApp">
        <test-method status="PASS" signature="getAccesstoken()[pri:0, instance:crm.telbiz.api.calls.TestApp@4fccd51b]" name="getAccesstoken" is-config="true" duration-ms="3783" started-at="2018-12-24T12:46:51Z" finished-at="2018-12-24T12:46:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAccesstoken -->
        <test-method status="FAIL" signature="ActivaeEbill()[pri:0, instance:crm.telbiz.api.calls.TestApp@4fccd51b]" name="ActivaeEbill" duration-ms="1468" started-at="2018-12-24T12:46:55Z" finished-at="2018-12-24T12:46:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SUCCESS] but found [FAIL]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at crm.telbiz.api.calls.TestApp.ActivaeEbill(TestApp.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at crm.telbiz.api.calls.Sheduler.main(Sheduler.java:16)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ActivaeEbill -->
        <test-method status="FAIL" signature="eEbillRegStatusAPI()[pri:0, instance:crm.telbiz.api.calls.TestApp@4fccd51b]" name="eEbillRegStatusAPI" duration-ms="708" started-at="2018-12-24T12:46:57Z" finished-at="2018-12-24T12:46:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SUCCESS] but found [FAIL]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at crm.telbiz.api.calls.TestApp.eEbillRegStatusAPI(TestApp.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at crm.telbiz.api.calls.Sheduler.main(Sheduler.java:16)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eEbillRegStatusAPI -->
      </class> <!-- crm.telbiz.api.calls.TestApp -->
    </test> <!-- testSmoke -->
  </suite> <!-- Smoke -->
</testng-results>
